config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'pages#home'

  post 'record/:mood' => 'pages#record_mood', as: :record_mood
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :moods
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def record_mood
    current_user.moods.create(mood: params[:mood])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mood Tracker
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//www.google.com/jsapi', 'chartkick'
    = csrf_meta_tags
  %body
    .container
      %h1.text-center Mood Tracker
    = yield

app/views/pages/home.html.haml
.container
  .row
    .twelve.columns
      .text-center
        %h3 What's your mood like right now?
        - (1..10).each do |i|
          = button_to i, record_mood_path(mood: i), { form_class: 'button-mood' }

%div{ style: 'width: 95%; height: 700px; margin: 0 auto;'}
  = line_chart current_user.moods.where('created_at > ?', 1.month.ago).pluck(:created_at, :mood), min: 0, max: 11, height: '450px', colors: ['#555555'],  library: { hAxis: { format: 'MMM d', gridlines: { count: -1, color: '#CCCCCC' } }, vAxis: { ticks: [1,2,3,4,5,6,7,8,9,10]}, pointSize: 3, curveType: 'none', theme: 'maximized', backgroundColor: { strokeWidth: 1 } }